Pulls and error on line 8 in my_collect_spec.rb
It should be "my_collection" instead of "my_collect"; throws this error:
1) my_collection yields the correct element from a given collection, in this case languages
     Failure/Error: my_collect(languages) do |language|
     NoMethodError:
       undefined method `my_collect' for #<RSpec::ExampleGroups::MyCollection:0x0000000291df78>
       Did you mean?  my_collection
     # ./spec/my_collect_spec.rb:15:in `block (2 levels) in <top (required)>'